import '../styles/globals.css'
import Head from 'next/head'

// components
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import ScrollToTop from '../components/ScrollToTop';

// context
import { ThemeContextProvider } from "../context/themeContext";
import WatchListContext from '../context/WatchListContext';
import SeachContextProvider from '../context/SearchContext';

// progree bar
import NextNProgress from 'nextjs-progressbar';


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Crypto Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favLogo.ico" />
      </Head>

      <ThemeContextProvider>
        <SeachContextProvider>
          <WatchListContext>
            <NextNProgress
              color="#29D"
              startPosition={0.3}
              stopDelayMs={200}
              height={3}
              showOnShallow={true}
            />
            <ScrollToTop />
            <Navbar />
            <Component {...pageProps} />
            <Footer />
          </WatchListContext>
        </SeachContextProvider>
      </ThemeContextProvider>

    </>
  )
}

export default MyApp
